name: Deploy to Firebase Functions on merge
on:
  push:
    branches:
      - main
    # paths:
    #   - 'functions/**'

defaults:
  run:
    working-directory: functions

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: discord-programing-event-bot
